config/routes.rb
 Rails.application.routes.draw do |map|
   resources :chimpactions, :except => [:show]
   match 'chimpactions/webhooks', :to => 'chimpactions#webhooks'
   match 'chimpactions/delete_webhook/:id', :to => 'chimpactions#delete_webhook'
   match 'chimpactions/add_webhook/:id', :to => 'chimpactions#add_webhook'
   match 'chimpactions/receive', :to => 'chimpacitons#receive', :as => :webhook
   match 'chimpactions/index', :to =>  'chimpactions#index'
 end

app/models/chimpaction.rb
require "chimpactions"

  class ResponseValidator < ActiveModel::Validator
    def validate(record)
      # k =  Kernel.const_get(Chimpactions::registered_class.name.to_s.capitalize).new
       k = Chimpactions.registered_class
      if k.respond_to?(record.action) != true
        record.errors[:action] << "- '#{record.action}' is not a method of #{k.class.name} !"
      end
      if k.respond_to?(record.whenn) != true
        record.errors[:whenn] << "- '#{record.whenn}' is not a method of #{k.class.name} !"
      end
    end
  end

# ActiveRecord 'wrapper' for Chimpactions::Action to provide non-yml peristence & customization
 class Chimpaction < ActiveRecord::Base
   validates_presence_of :list, :action, :whenn, :is, :value
   validates_with ResponseValidator
 end

app/controllers/chimpactions_controller.rb
class ChimpactionsController < ApplicationController
  def index
    @all_actions  = Chimpactions.actions
    @registered  = Chimpactions.registered_class_name
    @actions = Chimpaction.all
    @lists = Chimpactions.available_lists
  end
  
  # GET /chimpactions/new
  # GET /chimpactions/new.xml
  def new
    @chimpaction = Chimpaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chimpaction }
    end
  end

  # GET /chimpactions/1/edit
  def edit
    @chimpaction = Chimpaction.find(params[:id])
  end

  # POST /chimpactions
  # POST /chimpactions.xml
  def create
    @chimpaction = Chimpaction.new(params[:chimpaction])

    respond_to do |format|
      if @chimpaction.save
        format.html { redirect_to(chimpactions_url, :notice => 'Chimpaction was successfully created.') }
        format.xml  { render :xml => @chimpaction, :status => :created, :location => @chimpaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @chimpaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chimpactions/1
  # PUT /chimpactions/1.xml
  def update
    @chimpaction = Chimpaction.find(params[:id])

    respond_to do |format|
      if @chimpaction.update_attributes(params[:chimpaction])
        format.html { redirect_to(chimpactions_url, :notice => 'Chimpaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chimpaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chimpactions/1
  # DELETE /chimpactions/1.xml
  def destroy
    @chimpaction = Chimpaction.find(params[:id])
    @chimpaction.destroy

    respond_to do |format|
      format.html { redirect_to(chimpactions_url) }
      format.xml  { head :ok }
    end
  end
  
  def webhooks
    @lists = Chimpactions.available_lists
  end
  
  def add_webhook
    list = Chimpactions.list(params[:id])
     if list.set_webhook :url => 'http://www.postbin.org/1iwea1s'#webhook_url
       flash[:notice] = "Added Webhook!"
     end
       redirect_to '/chimpactions/webhooks'
  end
  
  def delete_webhook
    list = Chimpactions.list(params[:id])
     if list.remove_webhook :url => 'http://www.postbin.org/1iwea1s' #webhook_url
       flash[:notice] = "Removed Webhook!"
     end
       redirect_to '/chimpactions/webhooks'
  end
  
  def receive
    if params['data']
      subscriber = Chimpactions.registered_class.find_by_email(params['data']['email'])
      subscriber.receive_webhook(params) if subscriber.respond_to?(:receive_webhook)
    end
      render :nothing => true
  end
# data[email] = 'federico@mailchimp.com'
# 
# data[email_type] = 'html'
# 
# data[id]  = 'da1b07ac4c'
# 
# data[ip_opt]='69.12.4.2'
# 
# data[list_id]='45a650bc63'
# 
# data[merges][EMAIL]='federico@mailchimp.com'
# 
# data[merges][FNAME] ='Federico'
# 
# data[merges][IP] ='127.0.0.1'
# 
# data[merges][LNAME]='Holgado'
# 
# data[merges][SIGNUP]=''
# 
# data[web_id]='234305517'
# 
# fired_at = '2011-06-30 02:34:35'
# 
# type ='profile'
  # end
  
end

app/views/chimpactions/_errors.html.erb
<% if target.errors.any? %>  
<div id="errorExplanation">  
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>  
  <ul>  
  <% target.errors.full_messages.each do |msg| %>  
    <li><%= msg %></li>  
  <% end %>  
  </ul>  
</div>  
<% end %>  

app/views/chimpactions/_form.html.erb
<style>
.ca_action_form {padding-bottom:25px;width:350px;}
.ca_action_form fieldset {background-color:inherit;padding:0px;margin:0px;}
.ca_action_form fieldset legend {background-color:inherit;}
.ca_action_form * {float:none;font-family: verdana, arial, helvetica, sans-serif;
  font-size:   12px!important;
  line-height: 14px!important;}
.ca_action_form label {padding:0 4px;}
.ca_action_form div {display:inline;}
.ca_action_form .field_with_errors input {border:1px solid red;}
.ca_action_form ol {list-style:none;padding:14px;margin: 0px auto;max-width:315px;}
.ca_action_form ol li{padding:4px;}
.ca_action_form .bold {font-weight:bold;}
</style>
<%= form_for @chimpaction, :html => {:class => 'ca_action_form'} do |c| %>
<%= render "chimpactions/errors", :target => @chimpaction %>
<fieldset>
  <ol>
    <li><%= c.label :when, {:class => 'bold'} %> <%= Chimpactions.registered_class_name%>.<%= c.text_field :whenn, {:size => '15'} %> </li>
    <li><%= select(:chimpaction, :is, %w(= < >)) %> <%= c.text_field :value %><%= c.label '(Value)' %></li>
    <li><%= c.label "THEN", {:class => 'bold'}%></li>
    <li><%= select(:chimpaction, :action, %w(add_to move_to remove_from).map {|l| [l.gsub('_',' ').titleize , l]}) -%></li>
    <li><%= collection_select(:chimpaction, :list, Chimpactions.available_lists, :name, :name)%></li>
    <li><%= submit_tag "submit"%></li>
</fieldset>
<% end %>

app/views/chimpactions/_list.html.erb
<style>
.ca_list {list-style:none;padding:0px;}
</style>
<ul class="ca_list">
  <li><%= list.name%> ( ID : <%= list.id %> )</li>
</ul>

app/views/chimpactions/edit.html.erb
<section>
<h1>EDIT Chimpaction : </h1>
<%= render :partial => 'form'%>
</section>

app/views/chimpactions/index.html.erb
<section>
  <% %w(notice warning error).each do |msg| %>
    <% unless flash[msg.to_sym].blank? %>
    <div class='message <%=msg-%>'><p><%=flash[msg.to_sym]-%></p></div>
    <% end %>
<% end %>
<h1>Current Chimpactions  : </h1>
<ul>
<% @actions.each do |action|%>
  <li> When a <%= @registered %> <%= action.whenn %> <%= action.is %> <%= action.value %> => <%= @registered%>.<%= action.action %> (<%= action.list %>) 
  <%= link_to 'Edit', edit_chimpaction_path(action) %> ||
   <%= link_to 'Destroy', chimpaction_path(action.id), :confirm => 'Are you sure?', :method => :delete %></li>
<%end%>
</ul>
</section>
<section>
  <h1> <%= link_to "Add New Chimpaction", new_chimpaction_path %> </h1>
</section>
<section>
  <h1>Your MailChimp lists: </h1>
  <%= render :partial => 'list', :collection => @lists if @lists.count > 0%>
</section>

app/views/chimpactions/new.html.erb
<section>
<h1>Create a Chimpaction : </h1>
<%= render :partial => 'form'%>
</section>

app/views/chimpactions/webhooks.html.erb
<style>
.ca_list {list-style:none;padding:0px;}
</style>
<div style="font-size:1.2em; color:green;"><%= flash[:notice] if flash[:notice] %></div>
<ul class="ca_list">
  <% @lists.each do |list|%>
  <li><%= list.name%> ( ID : <%= list.id %> )
    <% if list.webhook? == false %> 
      <%=link_to "Add Webhook", {:action => 'add_webhook', :id => list.web_id }%>
    <% else %>
      <%=link_to "REMOVE Webhook", {:action => 'delete_webhook', :id => list.web_id }%>
    <%end%>
  </li>
  <%end%>
</ul>

<div style="margin-top:25px;"> Remember !  : in order to do something here, your <%= Chimpactions.registered_class_name %> class must define :
  <pre> 
    ...
    def receive_webhook(post_from_mailchimp)
      // do something with the MailChimp POST data here
    end
    ...
  </pre>
  
</div>